import { Inter } from "next/font/google";
import React, { Suspense } from "react";
import Providers from "./providers";
import Loading from "./loading";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Home Page",
//     description: "Generated by create next app",
// };

const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <head>
                <title>Home Page</title>
            </head>
            <header></header>
            <body className={inter.className}>
                <Suspense fallback={<Loading />}>
                    <Providers>
                        {children}
                    </Providers>
                </Suspense>
            </body>
            <footer></footer>
        </html>


    );
}

export default RootLayout;
